### ISSUE TITLE
ProfileListener Conditional in Gradle 5.0

### ISSUE THREAD

**Issue by sghill** [nebula-plugins/gradle-nebula-integration#31] opened 2018-08-29 21:22 UTC
Is there a way for a plugin to ensure [StartParameter#setProfile(true)](https://docs.gradle.org/current/javadoc/org/gradle/StartParameter.html#setProfile-boolean-) is always enabled from a plugin?

I've tried setting it in the plugin, and from an initscript, but both seem to be too late.

[nebula-plugins/gradle-metrics-plugin](https://github.com/nebula-plugins/gradle-metrics-plugin) relies on `org.gradle.profile.ProfileListener#buildFinished(BuildProfile)` being executed to get timing information and upload results ([here](https://github.com/nebula-plugins/gradle-metrics-plugin/blob/master/src/main/java/nebula/plugin/metrics/collector/GradleCollector.java#L201)). 

https://github.com/gradle/gradle/commit/946a56b100aaf4901e9926c9b631dcb1bef7a3ec changed this behavior from being always called to only called when `--profile` is passed.

## Steps to Reproduce

1. `git clone https://github.com/nebula-plugins/gradle-metrics-plugin.git && cd gradle-metrics-plugin`
2. `./gradlew wrapper --gradle-version 5.0-20180829062852+0000`
3. `./gradlew check`

**Comment by ljacomet** [comment] 2018-09-04 16:35
@lptr Can you explain the rationale behind this and see the request from Netflix?

**Comment by ljacomet** [comment] 2018-09-04 16:36
Another idea: try with a settings plugin

**Comment by lptr** [comment] 2018-09-11 09:49
`ProfileListener` and the whole of `org.gradle.profile` is not public API, and as such Gradle makes no promise to keep these APIs or their behavior stable. Build scans are the preferred way to get information about build performance, and the profile report as it is now is going to be removed at some later point (most probably after we have a local alternative to build scans). I'm not aware of any plans to expose public APIs for third party code to collect its own metrics at this point.

There are public listeners that can be used to collect much of the same metrics, like `BuildListener`, `TaskExecutionListener` etc.

**Comment by rpalcolea** [comment] 2018-09-12 21:50
Hi @lptr,

We use the `ProfileListener` to get information such as elapsed times -> https://github.com/nebula-plugins/gradle-metrics-plugin/blob/master/src/main/java/nebula/plugin/metrics/collector/GradleCollector.java#L138

Looking into `BuildListener` found that `buildFinished` returns a `BuildResult` (https://docs.gradle.org/current/javadoc/org/gradle/BuildResult.html) which lacks of these details. Since `org.gradle.profile` is not a public API, is there one to retrieve this information?

**Comment by rpalcolea** [comment] 2018-09-12 23:46
On a quick note, doing `./gradlew --profile integrationTest` doesn't work either.

Steps to Reproduce
===

```
git clone https://github.com/nebula-plugins/gradle-metrics-plugin.git && cd gradle-metrics-plugin
./gradlew wrapper --gradle-version 5.0-20180912002106+0000
./gradlew --profile check
```

**Comment by ljacomet** [comment] 2018-09-13 17:10
I had a look and did a few experiments. Unless `--profile` is passed on the command line, there is no way to tweak the `StartParameter` instance to make sure the `ProfileEventAdapter` is registered properly, enabling `ProfileListener` to be added and notified.

Given that we are deprecating the profile in favor of build scans, you will most likely have to duplicate some of the logic in `ProfileEventAdapter` for your own usage. Still looking if we have the right public APIs for doing that. Will get back to you as soon as I have a complete answer.

**Comment by rpalcolea** [comment] 2018-09-13 17:16
Thanks for looking into this @ljacomet. Let me know if you also get a chance to check why `StartParameter.profile` is not getting populated when provided `--profile` as mentioned in https://github.com/nebula-plugins/gradle-nebula-integration/issues/31#issuecomment-420834976

**Comment by ljacomet** [comment] 2018-09-14 13:03
I cannot reproduce this, when I set a [breakpoint in `DefaultGradleLauncherFactory`](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleLauncherFactory.java#L151), I can see that `startParameter.isProfile()` returns `true`

**Comment by rpalcolea** [comment] 2018-09-14 16:51
@ljacomet, weird... now it works (the `isProfile()` flag). Wonder if Intellij gave me a hard time. Still, with `--profile` seems that the plugin still broken. 

One thing that I notice is that `profile` is populated when starting execution. However, once Gradle tries to execute the `integrationTest` task, the `profile` flag is not populated as part of `StartParameter`. For that reason our integration tests never pass the `startParameter.isProfile()` in `DefaultGradleLauncherFactory`. 

Also this happens in Gradle 4.10 so I guess is a expected behavior? I'm not very familiar with the internals of Gradle on that portion. is `DefaultBuildOperationExecutor` responsible for executing the integration test task? if that's the case... does it mean it doesn't pass the original `--profile` argument?

I captured the debug log here -> https://gist.github.com/rpalcolea/821db5dc99111c3f959efb56b55a5c91 but couldn't find anything meaningful so far.

Also I'm attaching a few screenshots from my debugger.

![screen shot 2018-09-14 at 9 40 20 am](https://user-images.githubusercontent.com/1625920/45563885-8de7ee00-b803-11e8-969f-d4e20cd3ac3b.png)
![screen shot 2018-09-14 at 9 40 37 am](https://user-images.githubusercontent.com/1625920/45563886-8de7ee00-b803-11e8-8ff0-360315b5202f.png)
![screen shot 2018-09-14 at 9 40 43 am](https://user-images.githubusercontent.com/1625920/45563887-8de7ee00-b803-11e8-9902-1cb2ba4d9e45.png)

With that said, looks like the nature of Gradle is to not populate `profile` when executing the task, is that correct? If, yes I guess the Settings Plugin is not an option and we would need a public API to collect this informaton somehow. Did you get a chance to look at that potential option?

Thanks again for looking into this.

**Comment by lptr** [comment] 2018-09-18 09:14
@rpalcolea I'm not just suggesting implementing `BuildListener` alone, but to implement all of these public listeners:

- `BuildListener`
- `ProjectEvaluationListener`
- `TaskExecutionListener`
- `DependencyResolutionListener`

These should give you a lot of information that you are currently getting from the profile report. You can use `ProfileEventAdapter` as a guideline for your implementation. You will need your own data structures to collect the stats, too. In essence, you'll need to create your own `BuildProfile`.

If you do this, you'll have a listener you can register that uses only public APIs and does not depend on the `--profile` option.

**Comment by rpalcolea** [comment] 2018-09-18 17:17
Thanks for the insight @lptr 

We will dig into this and keep you posted

**Comment by rpalcolea** [comment] 2018-10-09 00:36
As discussed Today, opened https://github.com/gradle/gradle/issues/7138

**Comment by rpalcolea** [comment] 2018-10-29 15:45
Per @bigdaz suggestion, we are using `org.gradle.internal.scan.time.BuildScanBuildStartedTime` now and also removed the usage of `BuildScopeServices` and `BuildCompletionListener`.

Closing this now

**Comment by ljacomet** [comment] 2018-10-29 15:53
In fact @bigdaz added the public API for this and it will be part of Gradle 5.0 - see gradle/gradle#7504

**Comment by rpalcolea** [comment] 2018-10-29 15:55
fantastic! thanks for the heads up

**Comment by rpalcolea** [comment] 2018-11-02 23:37
Opened an issue in Gradle -> https://github.com/gradle/gradle/issues/7613 and created a sample project to reproduce this -> https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/build-started-listener-issue

@lptr @bigdaz @ljacomet  ^^

**Comment by rpalcolea** [comment] 2018-11-03 00:44
From comments in https://github.com/gradle/gradle/issues/7613#issuecomment-435543968

It is recommended to not use `buildStarted` since it is something that should be removed soon.

closing this again since we are working on removing this dependency

**Closed by rpalcolea** 2018-11-03 00:44 UTC
