### ISSUE TITLE
Excludes defined for individual dependencies are being overridden by dependecyManagement section

### ISSUE THREAD

**Issue by chali** [nebula-plugins/gradle-nebula-integration#1] opened 2018-07-31 17:54 UTC
Reported in gradle project:https://github.com/gradle/gradle/issues/6128
Possibly related issue: https://github.com/gradle/gradle/issues/5466
Example project: https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/excludes-with-bom

**Comment by ljacomet** [comment] 2018-08-01 12:40
I believe the first issue should be gradle/gradle#6128 and not gradle/gradle#5467. And I confirm that gradle/gradle#5466 has the same root cause.

And gradle/gradle#6158 has been opened to fix this issue.

**Comment by chali** [comment] 2018-08-02 18:25
Thanks, I updated original description.

**Comment by ljacomet** [comment] 2018-08-06 10:45
The fix for this issue has now been merged and will be released with Gradle 4.10-rc1

**Comment by sghill** [comment] 2018-08-11 15:16
Confirmed fixed in Gradle 4.10-rc-1. Thanks @ljacomet!

**Closed by sghill** 2018-08-11 15:16 UTC
